services:
  postgres:
    image: postgres:13
    container_name: hive-metastore-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
    volumes:
      - ./postgres/init-hive-metastore.sql:/docker-entrypoint-initdb.d/init-hive-metastore.sql
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hadoop-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/servers.json:/pgadmin4/servers.json
      - ./postgres/.pgpass:/var/lib/pgadmin/.pgpass
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - hadoop-network

  namenode:
    build:
      context: .
      dockerfile: hadoop.Dockerfile
    container_name: namenode
    hostname: namenode
    environment:
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_USER=root
      - HADOOP_SSH_OPTS="-o StrictHostKeyChecking=no"
    volumes:
      - ./hadoop/namenode/data:/home/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"
      - "2222:22"
    networks:
      - hadoop-network
    extra_hosts:
      - "namenode:172.18.0.2"
      - "datanode:172.18.0.3"
      - "resourcemanager:172.18.0.6"

  datanode:
    build:
      context: .
      dockerfile: hadoop.Dockerfile
    container_name: datanode
    hostname: datanode
    environment:
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
    volumes:
      - ./hadoop/datanode/data:/home/hadoop/dfs/data
    ports:
      - "9864:9864"
      - "2223:22"
    networks:
      - hadoop-network
    extra_hosts:
      - "namenode:172.18.0.2"
      - "datanode:172.18.0.3"
      - "resourcemanager:172.18.0.6"

  hive:
    build:
      context: .
      dockerfile: hive.Dockerfile
    container_name: hive-server
    environment:
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hiveuser
      - POSTGRES_PASSWORD=hivepassword
      - TMPDIR=/tmp/gunicorn
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 40s
      timeout: 50s
      retries: 5
    depends_on:
      - postgres
      - namenode
      - datanode
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - hadoop-network

  hue:
    image: gethue/hue:latest
    container_name: hue
    command: /usr/share/hue/build/env/bin/supervisor
    environment:
      - TMPDIR=/tmp
      - HUE_CONF_DIR=/usr/share/hue/desktop/conf
      - HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=true
      - HUE_DATABASE=postgres
      - HUE_DATABASE_USER=hueuser
      - HUE_DATABASE_PASS=hivepassword
      - HUE_DATABASE_DB=hue
      - HUE_SECRET_KEY=secret
    volumes:
      - ./hue/hue.ini:/usr/share/hue/desktop/conf/hue.ini:ro
    ports:
      - "8888:8888"
    depends_on:
      hive:
        condition: service_healthy
    networks:
      - hadoop-network

  spark:
    build:
      context: .
      dockerfile: spark.Dockerfile
    container_name: spark
    depends_on:
      - postgres
      - namenode
      - datanode
    ports:
      - "4040:4040"
      - "4041:4041"
      - "18080:18080"
      - "5555:5555"
      - "8089:8080"
    networks:
      - hadoop-network

  resourcemanager:
    build:
      context: .
      dockerfile: hadoop.Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      - YARN_RESOURCEMANAGER_HOST=resourcemanager
      - YARN_NODEMANAGER_HOST=nodemanager
    ports:
      - "8088:8088"
    networks:
      - hadoop-network
    depends_on:
      - namenode
      - datanode
    extra_hosts:
      - "namenode:172.18.0.2"
      - "datanode:172.18.0.3"
      - "resourcemanager:172.18.0.6"

  nodemanager:
    build:
      context: .
      dockerfile: hadoop.Dockerfile
    container_name: nodemanager
    hostname: nodemanager
    environment:
      - YARN_RESOURCEMANAGER_HOST=resourcemanager
      - YARN_NODEMANAGER_HOST=nodemanager
    ports:
      - "8042:8042"
    networks:
      - hadoop-network
    depends_on:
      - resourcemanager

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    networks:
      - hadoop-network

  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    container_name: jupyter-notebook
    ports:
      - "8889:8888"
    depends_on:
      - spark
      - minio
    volumes:
      - ./python_scripts:/home/jovyan/work
    networks:
      - hadoop-network

  livy:
    build:
      context: .
      dockerfile: spark.Dockerfile
    container_name: livy
    ports:
      - "8998:8998"
    depends_on:
      - spark
    networks:
      - hadoop-network
    entrypoint: ["/opt/spark/bin/livy-server"]

  admin-panel:
    build:
      context: ./admin_panel
    container_name: admin-panel
    ports:
      - "8501:8501"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge
    name: hadoop-network
