apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out old_k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nodemanager
  name: nodemanager
spec:
  ports:
    - name: "8042"
      port: 8042
      targetPort: 8042
  selector:
    io.kompose.service: nodemanager
