apiVersion: v1
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL-HiveMetastore",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "MaintenanceDB": "metastore",
          "Username": "hiveuser",
          "SSLMode": "prefer",
          "PassFile": "/var/lib/pgadmin/.pgpass"
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: pgadmin
  name: pgadmin-cm0
