apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out old_k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: spark
  name: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out old_k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: spark
    spec:
      containers:
        - image: spark
          name: spark
          ports:
            - containerPort: 4040
              protocol: TCP
            - containerPort: 4041
              protocol: TCP
            - containerPort: 18080
              protocol: TCP
            - containerPort: 5555
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
