# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - "/media/satish/New Volume/mysql_docker/data/mysql:/var/lib/mysql"
      - "/media/satish/New Volume/mysql_docker/config_files/init.sql:/docker-entrypoint-initdb.d/init.sql"  # Add this line to execute SQL script on startup
    command: --init-file /docker-entrypoint-initdb.d/init.sql