# Enable Spark Event Logging
spark.eventLog.enabled=true
spark.eventLog.dir=file:///opt/spark/event_logs
spark.history.fs.logDirectory=file:///opt/spark/event_logs

# HDFS & Hive Metastore Warehouse Configuration
spark.sql.catalogImplementation=hive
spark.hadoop.fs.defaultFS=hdfs://namenode:9000
spark.sql.warehouse.dir=hdfs://namenode:9000/user/hive/warehouse

# Delta Lake System-Wide Configurations
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog

# Cluster Resource Controls & Dynamic Resource Allocation (DRA)
spark.deploy.defaultCores=1
spark.dynamicAllocation.enabled=true
spark.dynamicAllocation.shuffleTracking.enabled=true
spark.dynamicAllocation.executorIdleTimeout=30s
spark.dynamicAllocation.cachedExecutorIdleTimeout=60s
spark.dynamicAllocation.minExecutors=0
spark.dynamicAllocation.maxExecutors=12

# MinIO (S3A) Configurations
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.access.key=minioadmin
spark.hadoop.fs.s3a.secret.key=minioadmin123
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.driver.memory=4g
spark.executor.memory=8g
spark.executor.cores=6
spark.cores.max=12
spark.sql.shuffle.partitions=200
spark.sql.adaptive.enabled=true
spark.sql.adaptive.coalescePartitions.enabled=true
spark.memory.fraction=0.8
spark.memory.storageFraction=0.5
