SELECT 'CREATE DATABASE metastore' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'metastore')\gexec
CREATE USER IF NOT EXISTS hiveuser WITH PASSWORD 'hivepassword';
GRANT ALL PRIVILEGES ON DATABASE metastore TO hiveuser;

SELECT 'CREATE DATABASE hue' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'hue')\gexec
CREATE USER IF NOT EXISTS hueuser WITH PASSWORD 'huepassword';
GRANT ALL PRIVILEGES ON DATABASE hue TO hueuser;
