[theme]
base = "dark"
primaryColor = "#6366f1"
backgroundColor = "#07090e"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1024000
